In [1]:
import numpy as np
import pandas as pd

In [5]:
# Create a 3x3 Matrix

mat = np.arange(21,30).reshape(3,3)
print(mat)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [7]:
# Transpose of a matrix

mat.transpose()

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [9]:
# Matrix Multiplication

A = np.arange(21, 30).reshape(3, 3)
B = np.arange(41, 50).reshape(3, 3)

A.dot(B)

array([[2910, 2976, 3042],
       [3306, 3381, 3456],
       [3702, 3786, 3870]])

In [10]:
B.dot(A)

array([[3030, 3156, 3282],
       [3246, 3381, 3516],
       [3462, 3606, 3750]])

In [15]:
C = np.arange(41,47).reshape(3,2)